dubbo:
  application:
    logger: slf4j
    name: dubbo-order
    qos-port: 2221
  registry:
    address: nacos://localhost:8848?namespace=06dd5361-9d44-4532-ab22-08140799af90
    parameters:
      namespace: 06dd5361-9d44-4532-ab22-08140799af90
  protocol:
    name: dubbo
    port: 50055
server:
  port: 9086
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/lab_order?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root_123
      initial-size: 5
      min-idle: 5
      max-active: 20