dubbo:
  application:
    logger: slf4j
    name: dubbo-good
    qos-port: 2223
  registry:
    address: nacos://localhost:8848?namespace=06dd5361-9d44-4532-ab22-08140799af90
    parameters:
      namespace: 06dd5361-9d44-4532-ab22-08140799af90
  protocol:
    name: dubbo
    port: 50052
server:
  port: 9082